---

name: create-git-tag
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  create-git-tag:
    uses: "MarcTBeneva/create-git-tag-reusable-workflow/.github/workflows/create-git-tag-common.yml@main"


...
