---

name: create-git-tag
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  create-git-tag:
    permissions: write-all  # Les permissions devront être revues.
    uses: "MarcTBeneva/create-git-tag-reusable-workflow/.github/workflows/create-new-tag.yml@main"


...
